version: '3.8'

services:
  king-1:
    image: david-1
    build: .
    ports:
      - '1000:7000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI || 'mongodb://localhost:27017

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
